catenax-ng/product-portal-frontend

.gitignore
Just added some more IDEs for .gitignore
=> Gitignore: Adding more IDEs with the help of gitignore.io

cx-portal-shared-components/src/components/basic/FilterSelector/FilterSelector.stories.tsx, cx-portal-shared-components/src/components/basic/FilterSelector/index.tsx
* New component for FilterSelector
* Story for Storybook
Note: Called it **FilterSelector** but it is more like a **ViewSwitcher** so maybe renaming can be done. Dumb component, logic for this should be in the portal.
=> CPLP-446: Filter Selector with Buttons & Story

cx-portal-shared-components/src/components/basic/ViewSelector/ViewSelector.stories.tsx, cx-portal-shared-components/src/components/basic/ViewSelector/index.tsx
* Renaming of the component to represent usage better
=> CPLP-449: Renaming component to better indicate usage

cx-portal/src/assets/locales/de/main.json, cx-portal/src/assets/locales/en/main.json, cx-portal/src/components/pages/MyAccount/index.tsx
in the "my account" page there is now a button to copy the encoded token into the clipboard
=> copy the JWT token to clipboard

.github/workflows/checks.yml, .husky/pre-commit
Github action checks workflow created
unit test command moved to checks workflow file
=> Recommendation for Unit test run at GH action

cx-portal/src/components/pages/AppMarketplace/components/FavoriteSection/index.tsx
Carousel for Favorite Application implemented
=> CPLP-451 Carousel for favorite app

cx-portal/src/assets/locales/de/main.json, cx-portal/src/assets/locales/en/main.json, cx-portal/src/components/pages/Admin/components/RegistrationRequests/CompanyDetailOverlay/index.tsx, cx-portal/src/components/pages/Admin/components/RegistrationRequests/index.tsx, cx-portal/src/components/pages/Admin/components/RegistrationRequests/registrationTableColumns.tsx, cx-portal/src/components/pages/PartnerNetwork/BusinessPartnerDetailOverlay/index.tsx, cx-portal/src/state/features/userAdministration/actions.ts, cx-portal/src/state/features/userAdministration/api.ts, cx-portal/src/state/features/userAdministration/slice.ts, cx-portal/src/state/features/userAdministration/types.ts
Registration requests table company detail overlay implemented
=> Feature CPLP-727 Company detail overlay implemented

cx-portal/src/state/features/userAdministration/api.ts
https://jira.catena-x.net/browse/CPLP-457 Registration Request Board
Change route of endpoints necessary due to renaming of useradministration service to administration service
=> CPLP-457: Change route of administration endpoints

cx-portal-shared-components/src/@types/styles.d.ts, cx-portal-shared-components/src/components/basic/Carousel/Carousel.stories.tsx, cx-portal-shared-components/src/components/basic/Carousel/index.tsx, cx-portal-shared-components/src/components/content/Cards/Card.tsx, cx-portal-shared-components/src/theme.ts, cx-portal/src/components/pages/AppMarketplace/components/FavoriteSection/index.tsx
- Card background color in Favorite
- Hover on Card, show Details button
- Adjust dots in Carousel Component to show Cards on mous hover
=> Bugfix/CPLP-925 fix Cards style in favorite apps

cx-portal/src/components/pages/UserManagement/AppUserDetails/index.tsx
Update data and comment to upcoming API
=> App User Detail

cx-portal-shared-components/src/components/content/Cards/Card.tsx, cx-portal-shared-components/src/components/content/Cards/CardButtons.tsx, cx-portal-shared-components/src/components/content/Cards/ContentCards.stories.tsx, cx-portal-shared-components/src/components/content/Cards/index.tsx, cx-portal/src/components/pages/AppMarketplace/components/AppListSection/index.tsx, cx-portal/src/components/pages/AppMarketplace/components/FavoriteSection/FavoriteItem.tsx, cx-portal/src/components/pages/AppMarketplace/components/FavoriteSection/index.tsx
- Add checkmark icon to card component in storybook component.
- add favorite item component
=> CPLP-947 add checkmark button to favorite cards

cx-portal/src/assets/locales/de/footer.json, cx-portal/src/assets/locales/de/main.json, cx-portal/src/assets/locales/en/footer.json, cx-portal/src/assets/locales/en/main.json, cx-portal/src/components/pages/Help/index.tsx
@nidhigarg-bmw  can you please do a quick check and in case there are no issues please approve the pr. Let me know in case you see any breaking issue
=> Update of locales

cx-portal/src/assets/locales/de/main.json, cx-portal/src/assets/locales/en/main.json, cx-portal/src/components/pages/EdcConnector/AddConnectorOverlay/components/ConnectorInsertForm.tsx, cx-portal/src/components/pages/EdcConnector/edcConnectorTableColumns.tsx
Translation typo fix
detail column sort feature disabled
Name field required rule fixed
=> Small hotfix for EDC connector page

cx-portal/src/components/pages/UserManagement/ActiveUserTable/index.tsx, cx-portal/src/components/pages/UserManagement/AppArea/index.tsx, cx-portal/src/components/pages/UserManagement/StageSubNavigation/StageSubNavigation.tsx
Add scroll to id in sub navigation links
=> CPLP-791 add scroll to id in sub navigation

cx-portal/src/services/EnvironmentService.ts
https://jira.catena-x.net/browse/CPLP-973
=> CPLP-973: Change to catenax-ng dev keycloak

cx-portal/src/services/EnvironmentService.test.ts, cx-portal/src/services/EnvironmentService.ts
https://jira.catena-x.net/browse/CPLP-1043
=> CPLP-1043: Pentest environment

cx-portal/src/components/pages/TechnicalUserManagement/index.tsx
* Adjusting modal/overlay behavior as requested by @jjeroch in https://jira.catena-x.net/browse/CPLP-793
=> CPLP-793: Adjusting overlay/modal behavior

cx-portal/src/features/digitalTwins/api.ts
Trivial change, to make the registry work.
=> FIX registry API url

cx-portal-shared-components/src/@types/styles.d.ts, cx-portal-shared-components/src/components/basic/CustomAccordion/CustomAccordion.stories.tsx, cx-portal-shared-components/src/components/basic/CustomAccordion/Item.tsx, cx-portal-shared-components/src/theme.ts
=> Add icon and fix style for accordion

cx-portal-shared-components/src/components/basic/SharedThemeProvider/index.tsx
* Hofix: Rearrange import order
=> Hotfix: Rearange import of sass:math

cx-portal-shared-components/src/components/basic/Dialog/DialogContent.tsx, cx-portal-shared-components/src/components/basic/Dialog/DialogHeader.tsx, cx-portal-shared-components/src/components/basic/Dialog/index.tsx
- Dialog Radius as props and default value is 10px
- Dialog Padding 32px
=> CPLP-1121 fix radius and padding in modal dialog

cx-portal/src/assets/locales/en/main.json
@lavanya-bmw could you please have a quick look and approve the pr if the changes have no syntax error
=> Update locales for technical user management

.gitignore, .vscode/settings.json, FILEHEADER.md
https://jira.catena-x.net/browse/CPLP-1161
=> CPLP-1161 Add instructions for file header

cx-portal-shared-components/src/@types/styles.d.ts, cx-portal-shared-components/src/components/content/Cards/CardAddService.stories.tsx, cx-portal-shared-components/src/components/content/Cards/CardAddService.tsx, cx-portal-shared-components/src/components/content/Cards/CardHorizontal.stories.tsx, cx-portal-shared-components/src/components/content/Cards/CardHorizontal.tsx, cx-portal-shared-components/src/components/index.tsx, cx-portal-shared-components/src/theme.ts
- Horizontal Card component added to storybook
=> Cplp 1206 horizontal card

cx-portal/src/assets/locales/de/main.json, cx-portal/src/assets/locales/en/main.json, cx-portal/src/components/overlays/InviteForm/InviteForm.stories.tsx, cx-portal/src/components/overlays/InviteForm/index.tsx, cx-portal/src/components/pages/InviteBusinessPartner/index.tsx, cx-portal/src/components/pages/SemanticHub/DownloadLink.tsx, cx-portal/src/components/pages/SemanticHub/ModelDetailDialog.tsx
Add the AAS-Download link for a semantic model, as defined in: https://jira.catena-x.net/browse/A1SLDT-391
Fixes Deletion Bug: https://jira.catena-x.net/browse/A1SLDT-692
=> Feature/AAS download-link in Semantic Hub

cx-portal-shared-components/src/components/basic/Progress/CircleProgress/CircleProgress.stories.tsx, cx-portal-shared-components/src/components/basic/Progress/CircleProgress/index.tsx, cx-portal-shared-components/src/components/index.tsx
Circle progress add has following props: 
-   step
-   interval
-   iteration
-   thickness
-   size
-   color
-   variant
=> Feature/cplp 1280 Circle Progress

cx-portal-shared-components/package.json, cx-portal/package.json, package.json
increase version to match current sprint PI 5, Sprint 1
=> bumped version to 0.5.1

cx-portal/src/assets/locales/de/main.json, cx-portal/src/assets/locales/en/main.json, cx-portal/src/components/overlays/InviteForm/InviteForm.stories.tsx, cx-portal/src/components/overlays/InviteForm/index.tsx, cx-portal/src/components/pages/InviteBusinessPartner/index.tsx, cx-portal/src/components/pages/UserManagement/UserDetails/index.tsx, cx-portal/src/components/shared/frame/PageBreadcrumb/PageBreadcrumb.tsx
Breadcrumb component improved to read the full path from router and create breadcrumb items.
=> Feature/cplp 509 Enabling Breadcrumb

cx-portal-shared-components/src/@types/styles.d.ts, cx-portal-shared-components/src/components/basic/Stepper/Stepper.stories.tsx, cx-portal-shared-components/src/components/basic/Stepper/StepperItem.tsx, cx-portal-shared-components/src/components/basic/Stepper/index.tsx, cx-portal-shared-components/src/components/index.tsx, cx-portal-shared-components/src/theme.ts
Add Stepper Component with props:
- List of steps and titles
- Number of steppes to show
- active step number
=> Feature/cplp 809 Stepper

cx-portal-shared-components/src/components/basic/Progress/CircleProgress/CircleProgress.stories.tsx, cx-portal-shared-components/src/components/basic/Progress/CircleProgress/index.tsx
change props Color to ColorVariant (Select list)
=> Progress Component: Change Color props name

cx-portal/src/components/pages/AppReleaseProcess/AppReleaseProcess.scss
Just remove footer background. Its now transparent.
=> CPLP-1293 fix footer background

cx-portal/src/components/pages/AppMarketplace/components/FavoriteSection/index.tsx, cx-portal/src/components/pages/AppMarketplace/components/StageSection/index.tsx, cx-portal/src/components/pages/AppMarketplace/index.tsx
- Old favorite removed from app marketplace
=> CPLP-1148 remove old favorite section

cx-portal/src/assets/locales/de/main.json, cx-portal/src/assets/locales/en/main.json, cx-portal/src/components/pages/Admin/components/RegistrationRequests/RegistrationRequests.test.tsx, cx-portal/src/components/pages/Admin/components/RegistrationRequests/index.tsx
Headline deleted and new introduction text added
=> HF Registration Request

cx-portal-shared-components/package.json, cx-portal/src/components/pages/Admin/components/RegistrationRequests/index.tsx, cx-portal/src/components/pages/Admin/components/RegistrationRequests/registrationTableColumns.tsx, cx-portal/src/components/pages/DigitalTwins/TwinTable.tsx, cx-portal/src/components/pages/EdcConnector/AddConnectorOverlay/components/ConnectorTypeSelection.tsx, cx-portal/src/components/pages/EdcConnector/index.tsx, cx-portal/src/components/pages/InviteBusinessPartner/index.tsx, cx-portal/src/components/pages/MyAccount/index.tsx, cx-portal/src/components/pages/PartnerNetwork/index.tsx, cx-portal/src/components/pages/SemanticHub/ModelTable.tsx, cx-portal/src/components/pages/TechnicalUserManagement/TechnicalUserTable/index.tsx, cx-portal/src/components/pages/UserManagement/AddUserRightOverlay/UserListContent.tsx, cx-portal/src/components/pages/UserManagement/AppUserDetails/components/AppUserDetailsTable/index.tsx, cx-portal/src/components/pages/UserManagement/UserDetails/index.tsx, yarn.lock
- Add UniqueId to all tables
- Upgrade @mui/x-data-grid to 5.15, beacuse last Version has Error (see: https://github.com/mui/mui-x/issues/4324)
- Fix Error in Typography component. (Typography component can't have children)
=> Bug fix/Fix console errors

.github/workflows/build.yml
https://jira.catena-x.net/browse/CPLP-1074
=> CPLP-1074: Enable auto image update for portal frontend

.github/workflows/release.yml
https://jira.catena-x.net/browse/CPLP-1074
=> CPLP-1074: Add dispatch to release workflow

cx-portal-shared-components/src/components/basic/Carousel/CarouselBox.tsx, cx-portal/src/components/pages/Admin/components/RegistrationRequests/index.tsx, cx-portal/src/components/pages/Admin/components/RegistrationRequests/registrationTableColumns.tsx, cx-portal/src/components/pages/InviteBusinessPartner/index.tsx
- Fix error in Application request table
- Change params.id to params.row.id
- Fix Created Date in inviteBussinessPartner Table
=> Bug fix/cplp 1344 table fix unique id

cx-portal-shared-components/package.json, cx-portal-shared-components/src/components/basic/Datepicker/Datepicker.stories.tsx, cx-portal-shared-components/src/components/basic/Datepicker/index.tsx
=> Feature/cplp 1296 Datepicker Component

cx-portal/src/components/overlays/EditAppUserRoles/index.tsx, cx-portal/src/components/overlays/EditAppUserRoles/style.scss, cx-portal/src/components/pages/AppMarketplace/components/FavoriteSection/index.tsx, cx-portal/src/features/apps/apiSlice.ts
added rtk query hook for app favorites
prettier touched a few unrelated files
=> fixed app favorites

cx-portal-shared-components/src/theme.ts
=> CPLP-1357 Fix Modal Dialog header style

cx-portal/src/components/pages/AppReleaseProcess/components/AppMarketCard/AppMarketCard.scss, cx-portal/src/components/pages/AppReleaseProcess/components/AppMarketCard/index.tsx
=> CPLP-1365 fix card class name

cx-portal/src/components/pages/AppMarketplace/components/StageSection/index.tsx, cx-portal/src/components/pages/Home/components/StageSection/index.tsx, cx-portal/src/components/pages/UserManagement/StageSection/index.tsx, cx-portal/src/components/styles/_stage.scss
CSS class stage-section is no more needed. We use header component and the style is in this component implemented.
=> CPLP-1366 remove stage-section class

cx-portal-shared-components/src/theme.ts, cx-portal/src/assets/locales/de/main.json, cx-portal/src/assets/locales/en/main.json, cx-portal/src/components/pages/AppReleaseProcess/components/AppMarketCard/index.tsx
-Change success color
-Change adduser helperText between the en-de
=> Bug fix/cplp 1340 button color

cx-portal-shared-components/src/components/basic/Datepicker/index.tsx, cx-portal-shared-components/src/theme.ts
Poper Width in multi select list fixed
=> Bug fix/fix multi select popper

cx-portal-shared-components/src/components/basic/Table/components/Toolbar/index.tsx, cx-portal-shared-components/src/components/basic/Table/index.tsx
it broke with Feras' implementation of the UltimateToolbar
=> fixed maxRowsCount

cx-portal/src/components/overlays/AddUser/UserRoles.tsx
=> fixed comment

.github/workflows/build.yml, .github/workflows/trivy.yml
https://jira.catena-x.net/browse/CPLP-1432
=> CPLP-1432: Add latest tag to image for trivy scan

cx-portal/src/services/EnvironmentService.ts
https://jira.catena-x.net/browse/CPLP-1258
=> CPLP-1258: Add centralidp instances for beta and pre-prod

cx-portal-shared-components/dts/index.js, cx-portal-shared-components/package.json, cx-portal-shared-components/rollup.config.js, yarn.lock
added a tool to bundle and flatten the .d.ts files
=> fixed plugin license issue

cx-portal/src/components/shared/frame/Footer/index.tsx
Introduced another variable to handle footer background color
=> Footer background issue fix in User management page.

cx-portal/src/components/pages/AppDetail/components/AppDetailHeader/index.tsx
some file had unused imports which cause the linter to break the build
=> fix build breaking bug

cx-portal-shared-components/src/components/content/Cards/CardAddService.tsx
Create New App card style updates
=> Cplp 1621 design cleanups

cx-portal/src/services/EnvironmentService.ts
Add environments for bpdm
Align semantics with bpdm and centralidp
=> Add environments for if partner

cx-portal/src/components/pages/AppOverview/index.tsx
one duplicate and one unnecessary import are breaking the build
=> remove duplicate import

DEPENDENCIES, cx-portal-shared-components/README.md, cx-portal-shared-components/package.json, yarn.lock
see changes in package.json
DEPENDENCIES has some more changes - apparently that one hasn't been updated with some other change before
=> removed some peer dependencies

CHANGELOG.md, cx-portal-shared-components/package.json, cx-portal/package.json, package.json
https://jira.catena-x.net/browse/CPLP-1401
=> CPLP-1401: Introduce changelog

cx-portal/src/types/Constants.ts
Fixing the role which is used for service subscription. No update of the change log needed, change is too small.
=> Fix Service Marketplace - Service Subscription

cx-portal/src/features/appManagement/apiSlice.ts
@lavanya-bmw endpoint url was changed for the apprelease endpoint
=> HF api endpoint controller switch

cx-portal-shared-components/src/components/basic/ToolTips/index.tsx
Reducing the padding of the tooltip element.
Target: currently the padding (space between tooltip text and element frame) is quite huge. This change should reduce the padding
=> CPLP-UIComponent-Updating-Padding-Tooltips

cx-portal/src/services/EnvironmentService.test.ts, cx-portal/src/services/EnvironmentService.ts
https://jira.catena-x.net/browse/CPLP-1760
=> CPLP-1760: Change redirect for int keycloak

CHANGELOG.md, cx-portal-shared-components/src/components/basic/SelectList/index.tsx
Select list component: disable clear feature added as an optional parameter.
=> Select list component: disable clear feature added
